### ISSUE TITLE
Generate a trace file like this

### ISSUE THREAD

**Issue by licaiwei397** [ARM-software/SCALE-Sim#35] opened 2019-08-13 10:01 UTC
I want generate a file like this,what should i do for Scale-Sim,thank you very much.
![image](https://user-images.githubusercontent.com/39975865/62933216-45aac480-bdf4-11e9-8ae3-bd6f6a69116b.png)

**Comment by AnandS09** [comment] 2021-04-22 22:42
Hi @licaiwei397 : Apologies for missing this issue. 
Not sure if it is still relevant but let me answer regardless. 

If I am correct, the trace format of your file is: <address_hex> <FETCH/WRITE> <Cycle_count>

The traces generated by SCALE Sim follows this format: 
<cycle_count>, <addr1_int>, <addr2_int>, ..., <addrN_int>

The steps therefore to convert from SCALE_Sim to your format would be:

For each line in SCALE_sim: 
elem[0] == cycle_count
elem[1: N] = separate address

Thus you will generate N lines of your format per line of scalesim trace. 

The FETCH and WRITE will depend on the operand you are parsing. 
If the operands are IFMAP and FILTER you will FETCH. For OFMAP you will WRITE. 

I hope this helps! (Apologies for missing this issue) 

Thanks,
Anand

**Comment by AnandS09** [comment] 2021-04-22 22:43
@whatmough : Hi Paul, lets close this issue, as it is not a bug/enhancement for SCALE-Sim

**Closed** 2021-04-30 18:37 UTC
